#!/bin/bash

main() {
  check_fmt
  check_lint
}

check_fmt() {
  eval "set -e"
  for file in $(git ls-files '*.go') ; do
    gofmt -s $file | diff -u $file -
  done
  eval "set +e"
}

check_lint() {
  golangci-lint run ./...
}

main "$@"
