name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Go tests
    steps:
    - uses: actions/checkout@v6
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
    - name: Install dependencies
      run: |
        go install github.com/onsi/ginkgo/ginkgo@latest
        go install github.com/modocache/gover@latest
        go install github.com/mattn/goveralls@latest
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
    - name: Run tests
      run: |
        ginkgo -r -cover --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress
        ginkgo -tags=gorillamux -r --randomizeSuites --failOnPending --trace --race
        ginkgo -tags=gingonic -r --randomizeSuites --failOnPending --trace --race
        ginkgo -tags=echo -r --randomizeSuites --failOnPending --trace --race
        rm examples/examples.coverprofile
        bash scripts/fmtpolice
        gover
        goveralls -coverprofile=gover.coverprofile -repotoken gY90SprlNRGmSMl7MgybLreYa05wUXJTU
